[package]
name = "aricolor-rs"
version = "0.1.0"
authors = ["melliott209 <m.elliott92@yahoo.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
mockers = "0.23.0"
ratatui = "0.26.0"
